apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bgd-pr-testing
  namespace: openshift-gitops
spec:
  generators:
  - pullRequest:
      github:
        owner: jyotsanaarora
        repo: bgd
        labels:
        - preview
      requeueAfterSeconds: 300
  template:
    metadata:
      name: 'bgd-test-app'
    spec:
      source:
        repoURL: 'https://github.com/jyotsanaarora/bgd'
        targetRevision: 'HEAD'
        path: app/overlays/default/
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'bgd-test-app'
